---
- name: Start Airflow Services
  hosts: all
  become: yes
  vars_files:
    - roles/airflow/vars/main.yml
  tasks:
    - name: Start Airflow webserver
      shell: |
        cd {{ airflow_home }} && \
        sudo -u {{ airflow_user }} bash -c '. venv/bin/activate && AIRFLOW_HOME={{ airflow_home }} airflow webserver -D'
      when: inventory_hostname == 'server1'

    - name: Wait for services to start
      wait_for:
        timeout: 30
      
    - name: Start Airflow scheduler
      shell: |
        cd {{ airflow_home }} && \
        sudo -u {{ airflow_user }} bash -c 'export TZ=UTC && . venv/bin/activate && AIRFLOW_HOME={{ airflow_home }} airflow scheduler -D'
      when: inventory_hostname == 'server2'