---
- name: Deploy Airflow Webserver
  hosts: server1
  become: yes
  roles:
    - role: airflow
  vars:
    airflow_service: webserver

- name: Deploy Airflow Scheduler
  hosts: server2
  become: yes
  roles:
    - role: airflow
  vars:
    airflow_service: scheduler